http:
  middlewares:
    oidc-auth:
      plugin:
        traefik-oidc-auth:
          Secret: "${OIDC_SECRET}"
          SessionCookie:
            Domain: ".viggy96.me"
          Provider:
            Url: "https://id.viggy96.me"
            ClientId: "${OIDC_CLIENT_ID}"
            ClientSecret: "${OIDC_CLIENT_SECRET}"
          Scopes: ["openid", "profile", "email", "groups"]
          BypassAuthenticationRule: "PathRegexp(`^/api/.*`)"

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        customFrameOptionsValue: "SAMEORIGIN"
        stsSeconds: 15552000
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
      
    local-only:
      ipWhiteList:
        sourceRange:
        - "192.168.0.0/16"
        - "172.16.0.0/12"
        - "10.0.0.0/8"

    private:
      chain:
        middlewares:
          - default-headers
          - oidc-auth

    secure:
      chain:
        middlewares:
          - default-headers

tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      curvePreferences:
        - "CurveP521"
        - "CurveP384"
        - "X25519MLKEM768"
      cipherSuites:
        - "TLS_AES_256_GCM_SHA384"
        - "TLS_CHACHA20_POLY1305_SHA256"
          #- "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
          #- "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"

